version: '3.8'
services:

  php7-fpm:
    build:
      context: ./
      dockerfile: Dockerfile
    image: php7-fpm
    container_name: php7-fpm
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
    expose:
      - "9000"
